main_prompt_path: prompts/main_prompt.txt
rag_summarize_prompt_path: prompts/rag_summarize.txt
report_prompt_path: prompts/report_prompt.txt
router_prompt_path: prompts/router_prompt.txt
knowledge_prompt_path: prompts/knowledge_prompt.txt
diagnosis_prompt_path: prompts/diagnosis_prompt.txt
customer_prompt_path: prompts/customer_prompt.txt
